Ext.define('QuickStart.view.Localization', {

    localizations: {
        'nestoria.de': {
            favorites: 'Favoriten',
            history: 'Geschichte',
            search: 'Suche',
            filters: 'Filter',
            selectCity: 'Stadt auswählen',
            price: 'Preis',
            bathrooms: 'Badezimmer',
            bedrooms: 'Schlafzimmer',
            clearAll: 'Alles löschen',
            clearHistory: 'Klare geschichte',
            openSite: 'Site öffnen',
            city: 'Stadt',
            country: 'Land',
            date: 'Datum',
            clearFavorites: 'Favoriten löschen',
            nextPage: 'Nächste Seite',
            previousPage: 'Vorherige Seite',
            showHistory: 'Zeige die Geschichte',
            showFavorites: 'Favoriten anzeigen',
            toRent: 'mieten',
            toSale: 'zu verkaufen',
            deleteFavorite: 'Favoriten löschen',
            addFavorite: 'Favorit hinzufügen',
            detailed: 'Detailliert'
        },

        'nestoria.co.uk': {
            favorites: 'Favorites',
            history: 'History',
            search: 'Search',
            filters: 'Filters',
            selectCity: 'Select a city',
            price: 'Price',
            bathrooms: 'Bathrooms',
            bedrooms: 'Bedrooms',
            clearAll: 'Clear All',
            clearHistory: 'Clear History',
            openSite: 'Open Site',
            city: 'City',
            country: 'Country',
            date: 'Date',
            clearFavorites: 'Clear Favorites',
            nextPage: 'Next page',
            previousPage: 'Previous page',
            showHistory: 'Show history',
            showFavorites: 'Show Favorites',
            toRent: 'to rent',
            toSale: 'to sale',
            deleteFavorite: 'Delete favorite',
            addFavorite: 'Add favorite',
            detailed: 'Detailed'
        },

        'nestoria.com.br': {
            favorites: 'Favoritas',
            history: 'História',
            search: 'Procurar',
            filters: 'Filtros',
            selectCity: 'Selecione uma cidade',
            price: 'Preço',
            bathrooms: 'Banheiros',
            bedrooms: 'Quartos de dormir',
            clearAll: 'Limpar tudo',
            clearHistory: 'Limpar histórico',
            openSite: 'Site aberto',
            city: 'Cidade',
            country: 'País',
            date: 'Encontro',
            clearFavorites: 'Limpar Favoritos',
            nextPage: 'Próxima página',
            previousPage: 'Página anterior',
            showHistory: 'Mostrar histórico',
            showFavorites: 'Mostrar favoritos',
            toRent: 'alugar',
            toSale: 'à venda',
            deleteFavorite: 'Excluir favorito',
            addFavorite: 'Adicionar aos favoritos',
            detailed: 'Detalhado'
        },

        'nestoria.es': {
            favorites: 'Favoritas',
            history: 'Historia',
            search: 'Buscar',
            filters: 'Filtros',
            selectCity: 'Seleccione una ciudad',
            price: 'Precio',
            bathrooms: 'Los baños',
            bedrooms: 'Dormitorios',
            clearAll: 'Limpiar todo',
            clearHistory: 'Borrar historia',
            openSite: 'Sitio abierto',
            city: 'Ciudad',
            country: 'País',
            date: 'Fecha',
            clearFavorites: 'Borrar favoritos',
            nextPage: 'Siguiente página',
            previousPage: 'Pagina anterior',
            showHistory: 'Mostrar historial',
            showFavorites: 'Mostrar favoritos',
            toRent: 'rentar',
            toSale: 'venta',
            deleteFavorite: 'Eliminar favorito',
            addFavorite: 'Añadir favorito',
            detailed: 'Detallada'
        },

        'nestoria.fr': {
            favorites: 'Favoris',
            history: 'L\'histoire',
            search: 'Chercher',
            filters: 'Les filtres',
            selectCity: 'Sélectionnez une ville',
            price: 'Prix',
            bathrooms: 'Salle de bain',
            bedrooms: 'Chambres à coucher',
            clearAll: 'Tout effacer',
            clearHistory: 'Clear History',
            openSite: 'Histoire claire',
            city: 'Ville',
            country: 'Country',
            date: 'rendez-vous amoureux',
            clearFavorites: 'Effacer les favoris',
            nextPage: 'Page suivante',
            previousPage: 'Page précédente',
            showHistory: 'Afficher l\'histoire',
            showFavorites: 'Afficher les favoris',
            toRent: 'louer',
            toSale: 'vendre',
            deleteFavorite: 'Supprimer le favori',
            addFavorite: 'Ajouter un favori',
            detailed: 'Détaillé'
        },

        'nestoria.it': {
            favorites: 'Preferiti',
            history: 'Storia',
            search: 'Cerca',
            filters: 'Filtri',
            selectCity: 'Seleziona una città',
            price: 'Prezzo',
            bathrooms: 'Bagni',
            bedrooms: 'Camere da letto',
            clearAll: 'Cancella tutto',
            clearHistory: 'Cancella cronologia',
            openSite: 'Apri sito',
            city: 'Città',
            country: 'Paese',
            date: 'Data',
            clearFavorites: 'Cancella preferiti',
            nextPage: 'Pagina successiva',
            previousPage: 'Pagina precedente',
            showHistory: 'Mostra storia',
            showFavorites: 'Mostra Preferiti',
            toRent: 'affittare',
            toSale: 'alla vendita',
            deleteFavorite: 'Elimina preferito',
            addFavorite: 'Aggiungi preferito',
            detailed: 'Dettagliato'
        }
    },

    getLocalization(name) {
        if (name === 'nestoria.mx') {
            return this.localizations['nestoria.es'];
        }
        return (this.localizations[name]) ? this.localizations[name] : this.localizations['nestoria.co.uk'];
    }
});
